controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\Auth\LoginController::login

app_logout:
    path: /logout
    controller: App\Controller\Auth\LoginController::logout
registration:
    path: /registration
    controller: App\Controller\Auth\RegistrationController::registration

room:
    path: /room
    controller: App\Controller\Room\RoomController::room
